input_select:
  nettselskap:
    name: Nettselskap
    options:
      - Elvia
      - BKK
      - Norgesnett
      - Mellom
      - L-nett
      - Glitre Nett
      - Lede
      - Linja
      - Tensio
      - Noranett

  osnket_trinn:
    name: Ønsket trinn
    options:
      - 0-2 kWh
      - 2-5 kWh
      - 5-10 kWh
      - 10-15 kWh
      - 15-20 kWh

input_number:
  energy_target:
    name: Target Energy (kWh)
    min: 0.0
    max: 20.0
    step: 1.0
    mode: box

  price_0_2:
    name: Price 0-2 kWh
    min: 0
    max: 2000
    step: 1
    mode: box

  price_2_5:
    name: Price 2-5 kWh
    min: 0
    max: 2000
    step: 1
    mode: box

  price_5_10:
    name: Price 5-10 kWh
    min: 0
    max: 2000
    step: 1
    mode: box

  price_10_15:
    name: Price 10-15 kWh
    min: 0
    max: 2000
    step: 1
    mode: box

  price_15_20:
    name: Price 15-20 kWh
    min: 0
    max: 2000
    step: 1
    mode: box

  peak_day_1:
    name: Peak Day 1
    min: 0
    max: 2000.0
    step: 0.1
    mode: box

  peak_day_2:
    name: Peak Day 2
    min: 0
    max: 2000.0
    step: 0.1
    mode: box

  peak_day_3:
    name: Peak Day 3
    min: 0
    max: 2000.0
    step: 0.1
    mode: box

  current_hour_peak:
    name: Current Hour Peak
    min: 0
    max: 2000.0
    step: 0.1
    mode: box

  daily_highest_hour:
    name: Daily Highest Hour
    min: 0
    max: 2000.0
    step: 0.1
    mode: box

utility_meter:
  hourly_energy_usage:
    source: sensor.energy_consumed
    cycle: hourly

sensor:
  - platform: integration
    source: sensor.dynamic_power_sensor
    name: Energy Consumed
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      dynamic_energy_price_0_2:
        value_template: >
          {% set nettselskap = states('input_select.nettselskap') %}
          {% set prices = {
            'Elvia': 120,
            'BKK': 145,
            'Norgesnett': 115,
            'Mellom': 243,
            'L-nett': 285,
            'Glitre Nett': 155,
            'Lede': 262,
            'Linja': 275,
            'Tensio': 144,
            'Noranett': 360
          } %}
          {{ prices.get(nettselskap, 0) }}
        unit_of_measurement: "NOK"

      dynamic_energy_price_2_5:
        value_template: >
          {% set nettselskap = states('input_select.nettselskap') %}
          {% set prices = {
            'Elvia': 190,
            'BKK': 240,
            'Norgesnett': 191,
            'Mellom': 364,
            'L-nett': 285,
            'Glitre Nett': 195,
            'Lede': 262,
            'Linja': 343,
            'Tensio': 287,
            'Noranett': 510
          } %}
          {{ prices.get(nettselskap, 0) }}
        unit_of_measurement: "NOK"

      dynamic_energy_price_5_10:
        value_template: >
          {% set nettselskap = states('input_select.nettselskap') %}
          {% set prices = {
            'Elvia': 305,
            'BKK': 400,
            'Norgesnett': 314,
            'Mellom': 607,
            'L-nett': 435,
            'Glitre Nett': 335,
            'Lede': 449,
            'Linja': 411,
            'Tensio': 520,
            'Noranett': 740
          } %}
          {{ prices.get(nettselskap, 0) }}
        unit_of_measurement: "NOK"

      dynamic_energy_price_10_15:
        value_template: >
          {% set nettselskap = states('input_select.nettselskap') %}
          {% set prices = {
            'Elvia': 420,
            'BKK': 570,
            'Norgesnett': 560,
            'Mellom': 801,
            'L-nett': 585,
            'Glitre Nett': 690,
            'Lede': 633,
            'Linja': 686,
            'Tensio': 789,
            'Noranett': 860
          } %}
          {{ prices.get(nettselskap, 0) }}
        unit_of_measurement: "NOK"

      dynamic_energy_price_15_20:
        value_template: >
          {% set nettselskap = states('input_select.nettselskap') %}
          {% set prices = {
            'Elvia': 535,
            'BKK': 735,
            'Norgesnett': 744,
            'Mellom': 1008,
            'L-nett': 735,
            'Glitre Nett': 900,
            'Lede': 819,
            'Linja': 824,
            'Tensio': 1057,
            'Noranett': 1030
          } %}
          {{ prices.get(nettselskap, 0) }}
        unit_of_measurement: "NOK"

      monthly_peak_energy:
        value_template: >
          {% set peak_1 = states('input_number.peak_day_1') | float %}
          {% set peak_2 = states('input_number.peak_day_2') | float %}
          {% set peak_3 = states('input_number.peak_day_3') | float %}
          {{ (peak_1 + peak_2 + peak_3) / 3 }}
        unit_of_measurement: "kWh"

      current_energy_level:
        value_template: >
          {% set monthly_peak = states('sensor.monthly_peak_energy') | float(0) %}
          {% if monthly_peak <= 2 %}
            0-2 kWh
          {% elif monthly_peak <= 5 %}
            2-5 kWh
          {% elif monthly_peak <= 10 %}
            5-10 kWh
          {% elif monthly_peak <= 15 %}
            10-15 kWh
          {% elif monthly_peak <= 20 %}
            15-20 kWh
          {% else %}
            Above 20 kWh
          {% endif %}

      remaining_energy:
        value_template: >
          {% set current_hourly_usage = states('utility_meter.hourly_energy_usage') | float(0) %}
          {% set target = states('input_number.energy_target') | float(0) %}
          {{ target - current_hourly_usage }}
