automation:
  - id: "run_copy_script_every_30_minutes"  # Unique ID for the automation
    alias: "Run Copy Script Every 30 Minutes"
    trigger:
      - platform: time_pattern
        minutes: "/30"  # Triggers every 30 minutes
    action:
      - service: shell_command.copy_flows
      - delay: "00:00:10"  # Wait 10 seconds
      - service: hassio.addon_restart
        data:
          addon: "a0d7b954_nodered"

shell_command:
  copy_flows: 'bash /config/copy_flows.sh'
